import json
import glob
import pycurl

class Imagery(object):
    '''
        Imagery class, which will try to facilitate the sending of images to Facebook
    '''
    

    def __init__(self, token, input_path, output_path = './/'):
        self.token = token
        self.input_path = input_path
        self.output_path = output_path
        self._ids = []
    

    def __read_path(self):
        '''
            Method that reads the images in the inserted directory
        
            :param input_path: str
            :return list
        '''
        
        types = ['.jpg', '.png', '.bmp', '.gif', '.tiff']
        _images = []

        for _type in types:
            temp = glob.glob(self.input_path + '/*' + _type)
            
            for image in temp:
                _images.append(image)


        return _images


    def __gen_json(self, _id=0, end=False):
        '''
            Generates a json file with the IDS generated by the Facebook API
        
            :param output_path: str
            :return void
        '''

        # Set to true to save received ids
        if (end):
            if self.output_path[-1] == '/':
                self.output_path = self.output_path[:-1]
            with open(self.output_path + '/attachments.json', 'w') as output_file:
                json.dump(self._ids, output_file)    
        else:
            self._ids.append({'attachment_id': str(_id)[20:35]})
        

    def send_image(self):
        '''
            Upload images

            :param input_path: str
            :return void
        '''

        _url = 'https://graph.facebook.com/v2.6/me/message_attachments?access_token=' + self.token
        _images_to_send  = self.__read_path()

        c = pycurl.Curl()

        c.setopt(c.POST, 1)
        c.setopt(c.URL, _url)
        
        payload = '''
                {
                    "attachment" : {
                        "type" : "image" , 
                        "payload" : { "is_reusable" : true } 
                    } 
                }
                '''

        for image in _images_to_send:
            send = [('message', payload),
                    ('filedata', (pycurl.FORM_FILE, image))]
            c.setopt(c.HTTPPOST, send)
            c.setopt(pycurl.WRITEFUNCTION, self.__gen_json)
            c.perform()
        c.close()

        # Save a file with ids
        self.__gen_json(end=True)
