import glob
import requests

class Imagery(object):
    '''
        Imagery class, which will try to facilitate the sending of images to Facebook
    '''
    

    def __init__(self, token):
        self.token = token
    

    def __read_path(self, input_path):
        '''
            Method that reads the images in the inserted directory
        
            :param input_path: str
            :return void
        '''

        pass


    def __gen_json(self, output_path):
        '''
            Generates a json file with the IDS generated by the Facebook API
        
            :param output_path: str
            :return void
        '''

        pass


    def send_image(self, input_path):
        '''
            Upload images

            :param input_path: str
            :return void
        '''
        
        pass
    
    