import glob
import requests

class Imagery(object):
    '''
        Imagery class, which will try to facilitate the sending of images to Facebook
    '''
    

    def __init__(self, token, input_path, output_path = './'):
        self.token = token
        self.input_path = input_path
        self.output_path = output_path
    

    def read_path(self):
        '''
            Method that reads the images in the inserted directory
        
            :param input_path: str
            :return list
        '''
        
        types = ['.jpg', '.png']
        _images = []

        for _type in types:
            temp = glob.glob(self.input_path + '/*' + _type)
            
            for image in temp:
                _images.append(image)
        
        print(_images)

        # return _images


    def __gen_json(self, output_path):
        '''
            Generates a json file with the IDS generated by the Facebook API
        
            :param output_path: str
            :return void
        '''

        pass


    def send_image(self):
        '''
            Upload images

            :param input_path: str
            :return void
        '''

        pass
    
    